# eunsta 
<VirtualHost *:80>
    ServerName eunsta.local
    DocumentRoot /var/www/html/eunsta/web
    <Directory /var/www/html/eunsta/web>
        AllowOverride All
        Order Allow,Deny
        Allow from All
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/eunsta_error.log
    CustomLog ${APACHE_LOG_DIR}/eunsta_access.log combined
</VirtualHost>

# Autogestion  
<VirtualHost *:80>
    ServerName alumnos.local
    DocumentRoot /var/www/html/Autogestion/web
    <Directory /var/www/html/Autogestion/web>
        AllowOverride All
        Order Allow,Deny
        Allow from All
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/autogestion_error.log
    CustomLog ${APACHE_LOG_DIR}/autogestion_access.log combined
</VirtualHost>